[variables]
NIXPACKS_PHP_VERSION = "8.2"

[phases.setup]
nixPkgs = ["php82", "php82Packages.composer"]

[phases.install]
cmds = [
  "composer install --no-dev --ignore-platform-reqs --optimize-autoloader"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"